version: '3.1'
services:
  db_cambio_service:
    image: mysql
    container_name: mysql_cambio_service
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '55000:3306'
    volumes:
      - cambio_service_data:/var/lib/mysql
  db_book_service:
    image: mysql
    container_name: mysql_book_service
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '56000:3306'
    volumes:
      - book_service_data:/var/lib/mysql
volumes:
  cambio_service_data:
  book_service_data: