server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
# para descoberta sem routerLocator
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true




